version: '3.8'

services:
  web:
    build: ./site  # Путь к папке с Dockerfile
    volumes:
      - ./site:/app      # Монтируем папку site
      - ./CNN:/app/CNN   # Монтируем папку CNN
    ports:
      - "8000:8000"